### ISSUE TITLE
selected-file-container should have this width in readonly state

### ISSUE THREAD

**Issue by adi130987** [unicef-polymer/etools-file#2]
```CSS
:host([readonly]) .selected-file-container {
    max-width: calc(100% - 145px);
}
```
